version: "3"
services:
  golang:
    image:  docker-adobe
    ports:
      - "8080:8080"
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3030:3030"